version: "3.7"

services:
  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    networks:
      - jotihunt
    labels:
      - traefik.enable = false

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 20

  jotihunt:
    image: avelderman/jotihunt:latest
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOSTNAME}/${MYSQL_DATABASE}
    networks:
      - jotihunt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jotihunt.rule=Host(`sbjotihunt.nl`)"
      - "traefik.http.routers.jotihunt.entrypoints=websecure"
      - "traefik.http.services.jotihunt-service.loadbalancer.server.port=3000"
      - "traefik.http.routers.jotihunt.tls.certresolver=myresolver"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.auth0.rule=Host(`sbjotihunt.nl`) && PathPrefix(`/auth0`)"
      - "traefik.http.routers.auth0.entrypoints=web"
      - "traefik.http.middlewares.auth0-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.auth0-redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.auth0-redirect.redirectscheme.port=443"
      - "traefik.http.middlewares.auth0-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.auth0-redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.auth0-redirect.redirectscheme.port=443"
      - "traefik.http.middlewares.auth0-redirect.redirectregex.regex=^/auth0/(.*)"
      - "traefik.http.middlewares.auth0-redirect.redirectregex.replacement=https://sbjotihunt.eu.auth0.com/$$1"
      - "traefik.http.routers.auth0.middlewares=auth0-redirect"
    depends_on:
      - "db"
    
  divinity:
    image: tristandb/divinity:latest
    container_name: divinity
    restart: always
    environment:
      - GOOGLE_SERVER_AUTH_TOKEN
      - GOOGLE_CLIENT_AUTH_TOKEN
      - JOTIHUNT_HOST=http://localhost:3000
    networks:
      - jotihunt
    depends_on:
      - jotihunt
    labels:
      - traefik.enable = false

  traefik:
    image: traefik:v2.9
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=${CF_API_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    environment:
      - CLOUDFLARE_EMAIL=${CF_API_EMAIL}
      - CLOUDFLARE_API_KEY=${CF_API_KEY}
      - C_COUNTER=1
    networks:
      - jotihunt

networks:
  jotihunt:
    name: jotihunt

volumes:
  dbdata:
